# Generated by Django 4.0.3 on 2022-03-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
    ]
